### ISSUE TITLE
Cant start server

### ISSUE THREAD

**Issue by M0n7y5** [Rfvgyhn/docker-avorion#10]
Hi i have problem with starting server.

When i run this command: 

```
docker run -d --name avorion \
   -p 27000:27000 \
   -p 27000:27000/udp \
   -p 27003:27003/udp \
   -p 27020:27020/udp \
   -p 27021:27021/udp \
   -v /host/path/saves:/home/steam/.avorion/galaxies/avorion_galaxy \
   rfvgyhn/avorion
```
I get this error:
`Failed to init logging in file: "/home/steam/.avorion/galaxies/avorion_galaxy/serverlog 2020-09-10 20-43-37.txt"
`

**Comment by Rfvgyhn** [comment]
What's the output before that point (run the container in attached mode or run `docker logs avorion`)? What are the permissions of your `host/path/saves` folder?

**Comment by M0n7y5** [comment]
So apparently this solved my problem 
`chown -R 1000 host/path/saves`
It would be good to add some info about it to Readme.md
