### ISSUE TITLE
Missing beta tag

### ISSUE THREAD

**Issue by M0n7y5** [Rfvgyhn/docker-avorion#13]
I cant download beta tag

**Comment by Rfvgyhn** [comment]
The repo doesn't have tags. If you mean from docker hub, there isn't a beta tag. The `latest` tag has the beta version if that's the newest. Or you can specify the exact version you want (e.g. `2.0.0.32316-beta`).

**Comment by M0n7y5** [comment]
I tried latest tag, but that gave me version 1.3.8

**Comment by M0n7y5** [comment]
But i see u already updated latest tag
