### ISSUE TITLE
SteamAPI_IsSteamRunning() failed

### ISSUE THREAD

**Issue by Laberbear** [rfvgyhn/docker-avorion#16]
This might not be related to this docker image but we are running into the following issue when trying to run it on our server.
Running Ubuntu 18.10

`

> $ docker run --name avorion -p 27000:27000 -p 27000:27000/udp -v /host/path/saves:/home/steam/.avorion/galaxies/avorion_galaxy_test -p 27003:27003/udp -p 27020:27020/udp -p 27021:27021/udp rfvgyhn/avorion
> Enabled Traces:
> Avorion server 2.0.9 15805b64fd6c running on Debian GNU/Linux 9 (stretch) starting up in "/home/steam/.avorion/galaxies/avorion_galaxy"
> Version Hash: 4850020235631032134
> CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz 8 Cores
> RAM: 31GB
> 
> Server version, as listed publicly: 2.0.9.34400
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
> RecordSteamInterfaceCreation (PID 1): SteamGameServer012 / GameServer
> RecordSteamInterfaceCreation (PID 1): SteamUtils008 / Utils
> Setting breakpad minidump AppID = 445220
> RecordSteamInterfaceCreation (PID 1): SteamGameServer012 / GameServer
> RecordSteamInterfaceCreation (PID 1): SteamUtils008 / Utils
> RecordSteamInterfaceCreation (PID 1): SteamNetworking005 / Networking
> RecordSteamInterfaceCreation (PID 1): SteamGameServerStats001 / GameServerStats
> RecordSteamInterfaceCreation (PID 1): STEAMHTTP_INTERFACE_VERSION002 / HTTP
> RecordSteamInterfaceCreation (PID 1): STEAMINVENTORY_INTERFACE_V001 / Inventory
> RecordSteamInterfaceCreation (PID 1): STEAMUGC_INTERFACE_VERSION008 / UGC
> RecordSteamInterfaceCreation (PID 1): STEAMAPPS_INTERFACE_VERSION008 / Apps
> Server failed to connect to Steam
> Server failed to connect to Steam

`

The server is still joinable via IP but does not show up on the browse server list and also complain that it uses deprecated (and highly unrecommended) old connection methods.

Thanks in advance!

**Comment by Rfvgyhn** [comment]
Did this just start happening or has it worked in the past? Does it also fail to connect to Steam if you use an older image (e.g. `rfvgyhn/avorion:stable`)? Does it happen if you run it on another server/computer?

I'm unable to replicate the issue on my server and my local machine. As long as I can remember, the `[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.` message has been around but the game still connects to Steam. Perhaps there's a firewall issue preventing a connection to Steam?

**Comment by Laberbear** [comment]
Thanks for the fast reply.
It does not happen when I run it on another server so clearly some weird connection issue must be happening on the host machine.

Sorry for the disruption here and have a good day!
