### ISSUE TITLE
[Update] new stable version available (v2.1)

### ISSUE THREAD

**Issue by lightlike** [rfvgyhn/docker-avorion#20]
Could you please update the container to the latest stable version of avorion?

Would it help if you had an automatic workflow?
I could look into that.

**Comment by rfvgyhn** [comment]
Stable and beta images should be updated.

An automatic workflow would be great. What I currently have is partially automated. I just run the `release.sh` script passing in the version and branch. Last time I looked (a long time ago), I couldn't find any sort of api that provided info on version updates. If you can find/build something like that, I'd definitely be open to a PR.

**Comment by lightlike** [comment]
I already looked into making one. I am not really used to the Github Actions Syntax but that shouldn't be so bad as I am working with Jenkins.

Easiest way to push the Container would be to the Github Container Registry as that dows not need any credentials.

I'm also currently debating what kind of trigger I want to use as thsi should be as automatic as possible.
It'll probably either need a manual trigger or run Daily using somthing like `https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/?appid=445220&count=1&tags=patchnotes` and comparing the date with `now() - 1d`.

I'll look into that over the next weeks when I have the time.
