### ISSUE TITLE
2.3.2 build

### ISSUE THREAD

**Issue by darkwind-noveo** [Rfvgyhn/docker-avorion#23]
Steam was updated to stable 2.3.2. new version needs to be built

P.S. nvm. built my own 2.3.2 in the mean time.
https://hub.docker.com/repository/docker/darkwind8/avorion/general

**Comment by dd84ai** [comment]
nvm. built my own 2.3.2 in the mean time.
https://hub.docker.com/repository/docker/darkwind8/avorion/general
