### ISSUE TITLE
server.ini not created on new Container

### ISSUE THREAD

**Issue by surtic86** [Rfvgyhn/docker-avorion#7]
Hi there,

I wanted to use your Docker Image to Host a Avorion Server. But it looks like when you want to BIND the Volume it won't generate a Server.ini.

When you run it without BIND it will work.

For me i fixed it with Copy the server.ini from the Running Container and Pasted it into my Folder.

Command:
`docker run -d --name avorion -p 27000:27000 -p 27000:27000/udp -p 27003:27003/udp -p 27020:27020/udp -p 27021:27021/udp -v /data/games/avorion/saves:/home/steam/.avorion/galaxies/avorion_galaxy rfvgyhn/avorion:stable`

Log:
`An exception occurred: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_13property_tree10ini_parser16ini_parser_errorEEEEE: /home/steam/.avorion/galaxies/avorion_galaxy/server.ini: cannot open file`

**Comment by Rfvgyhn** [comment]
I'm not able to replicate this issue. I've tested on my local arch machine and my remote ubuntu server. Are the permissions on `/data/games/avorion/saves` perhaps causing an issue?

**Comment by DASPRiD** [comment]
Had the same problem, but was actually just a permission issue – I created the mounted folder as root, but game runs under 1000:1000 :)

**Comment by Rfvgyhn** [comment]
Haven't heard back from you in while so I'm guessing this was a permissions issue. Feel free to re-open it if you think otherwise.

**Comment by M0n7y5** [comment]
This is still a problem

**Comment by Rfvgyhn** [comment]
@M0n7y5 Can you provide any details? What are the permissions on your data folder? Is it just the `server.ini` file that isn't working or are other files not working? How are you creating the container (docker run, docker-compose)?

**Comment by Pemboss** [comment]
I have this issue. I've pulled the image through to Portainer and all runs fine, can connect to server etc. As soon as I try to map the volumes for avorion_galaxy and backups I receive the erre: An exception occurred: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_13property_tree10ini_parser16ini_parser_errorEEEEE: /home/steam/.avorion/galaxies/avorion_galaxy/server.ini: cannot open file
