### ISSUE TITLE
I cant set myself as Admin

### ISSUE THREAD

**Issue by TheBombTuber** [Rfvgyhn/docker-avorion#9]
Hello,

i have the problem that i cant set myself as an admin on the avorion server.

I already tried to set up the admin.xml but it just get wiped clean after i start the server.

And i cant use the docker terminal to pass through any commands to the server.

Is there any other way to set me as admin??

I use docker on an synology ds218+

Thanks for the help.

**Comment by Rfvgyhn** [comment]
Is admin.xml getting wiped clean despite you mounting the data volume?

**Comment by TheBombTuber** [comment]
yes

**Comment by TheBombTuber** [comment]
all the other files are fine though

**Comment by Rfvgyhn** [comment]
I'm not sure what the cause is for that. It sounds like a server bug since all the other files are fine. You could try denying write permissions on the file. I don't know if that would cause a different problem though.

I'm not familiar with how docker is run on a synology, have you tried passing in the `--admin steamId` argument to the `ENTRYPOINT` of the docker container?

**Comment by TheBombTuber** [comment]
I will try denying the permission after changing the file in the morning.
And how do i pass the argument to the entrypoint?
I tried with exec and start but both didnt work

**Comment by Rfvgyhn** [comment]
It's passed in when you create the container. `docker run rfvgyhn/avorion --admin steamId` Or if you're using docker-compose, you can use the `command` option (`command: --admin steamId`).

**Comment by TheBombTuber** [comment]
I will try that tomorrow and let you know if it worked

**Comment by TheBombTuber** [comment]
Changing the permission after editing the admin.xml did nothing the server just made a new one.

And i tried creating the container with the admin command but it just tells me "unknown flag: --admin"

here is what i tried

`docker run -d --name avorion \
   -p 27000:27000 \
   -p 27000:27000/udp \
   -p 27003:27003/udp \
   -p 27020:27020/udp \
   -p 27021:27021/udp \
   -p 27001:27001 \
   -v /host/path/saves:/home/steam/.avorion/galaxies/avorion_galaxy \
   --admin 76561198066028464 \
   rfvgyhn/avorion`

i also tried

`docker run -d --name avorion --admin 76561198066028464 \
   -p 27000:27000 \
   -p 27000:27000/udp \
   -p 27003:27003/udp \
   -p 27020:27020/udp \
   -p 27021:27021/udp \
   -p 27001:27001 \
   -v /host/path/saves:/home/steam/.avorion/galaxies/avorion_galaxy \
   rfvgyhn/avorion`

am i doing it wrong??

**Comment by TheBombTuber** [comment]
I know what was wrong with the admin.xml now. I dont understand why but apparently i cant declare my ingame name as Admin.

This works
`<admin name="admin" id="76561198066028464"/>`

This does not work
`<admin name="TheBombTuber" id="76561198066028464"/>`

**Comment by Rfvgyhn** [comment]
Just for future reference, when you want to pass in additional arguments, they go after the image name.

```
docker run -d --name avorion \
    -p 27000:27000 \ 
    -p 27000:27000/udp \ 
    -p 27003:27003/udp \ 
    -p 27020:27020/udp \ 
    -p 27021:27021/udp \ 
    -p 27001:27001 \ 
    -v /host/path/saves:/home/steam/.avorion/galaxies/avorion_galaxy \ 
    rfvgyhn/avorion \
    --admin 76561198066028464
```
